# Generated by Django 5.0.7 on 2025-02-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='left_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='right_id',
            field=models.IntegerField(default=0),
        ),
    ]
