# Generated by Django 5.0.7 on 2025-02-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_category_order_alter_category_left_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productimage',
            order_with_respect_to=None,
        ),
    ]
