# Generated by Django 5.0.7 on 2025-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_alter_productimage_options_productimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_authorized',
            field=models.CharField(choices=[('Y', 'Yes'), ('?', 'Unknown'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
