# Generated by Django 5.0.7 on 2025-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_product_cost_product_is_authorized_product_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
