# Generated by Django 5.0.7 on 2025-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_product_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_parent',
            field=models.BooleanField(default=True),
        ),
    ]
