# Generated by Django 5.0.7 on 2025-09-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_category_show_in_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(default='anonymous', max_length=200)),
                ('image', models.ImageField(upload_to='poster_images')),
            ],
        ),        
    ]
