# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-01-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171130_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('year', 'release_date', 'name', 'media_format', 'country', 'catalog_number')},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='country',
            name='icon',
            field=models.ImageField(upload_to='countries'),
        ),
        migrations.AlterField(
            model_name='era',
            name='icon',
            field=models.ImageField(upload_to='eras'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='itemrarity',
            name='icon',
            field=models.ImageField(upload_to='rarity'),
        ),
        migrations.AlterField(
            model_name='itemrarity',
            name='scale_icon',
            field=models.ImageField(upload_to='rarity'),
        ),
        migrations.AlterField(
            model_name='mediaformat',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='musiclabel',
            name='icon',
            field=models.ImageField(null=True, upload_to='music_labels'),
        ),
        migrations.AlterField(
            model_name='report',
            name='icon',
            field=models.ImageField(upload_to='reports'),
        ),
    ]
