# Generated by Django 4.0.4 on 2022-05-14 05:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200111_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='track',
            name='related_tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='legnth',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='number',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='old_key',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
